version: "1.26.0"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql


  spring_app:
    image: bahriaraed/devops-integration
    container_name: devopscontainer
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb